email: services.beckers@gmail.com
title: Werkhuizen Beckers - Metaalbewerking
description: Maatwerk in staal, RVS en aluminium. Van ontwerp tot realisatie, inclusief CAD ontwerp en technische uitwerking.
baseurl: ""
url: ""
lang: nl-BE
markdown: kramdown
permalink: pretty

collections:
  projects:
    output: true
    permalink: /projecten/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      seo_type: CreativeWork
  - scope:
      path: ""
    values:
      layout: page

sass:
  style: compressed

exclude:
  - README.md
  - Gemfile.lock
  - node_modules
  - vendor
  - scripts
